<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
if($customerSession->isLoggedIn()) {
    $buttonTitle = __('Purchase Tickets');
} else {
    $buttonTitle = __('Login To Purchase');
}
?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div id="fiftyInformation" data-bind="scope:'fiftyInformation'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <input type="hidden" name="sku" value="<?= $_product->getSku() ?>" />
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Angel_Fifty/js/validate-fifty": {
                "loginUrl" : "<?= $block->getUrl('customer/account/login') ?>"
            }
        },
        "#fiftyInformation": {
            "Magento_Ui/js/core/app": {
                "components" : {
                    "fiftyInformation" : {
                        "component": "Angel_Fifty/js/view/purchase-ticket-popup",
                        "template": "Angel_Fifty/fifty-information",
                        "currentFiftyPrice": "<?= $_product->getPrice() ?>",
                        "currentPotPrice": "<?= $_product->getTypeInstance()->getCurrentPot($_product) ?>"
                    }
                }
            }
        }
    }

</script>