<?php
/**
 * @var $block \Angel\Fifty\Block\Product\View
 */
?>
<?php if ($block->isPending()): ?>
    <div><span id="fity_countdown" data-mage-init='{"angel/countdown": {"time_left":<?php echo $block->getTimeToStart() ?>}}'></span></div>
    <div><?= __('Start Pot: %1', $block->getCurrentPot()) ?> </div>
<?php elseif ($block->isProcessing()): ?>
    <div><span id="fity_countdown" data-mage-init='{"angel/countdown": {"time_left":<?php echo $block->getTimeLeft() ?>}}'></span></div>
    <div><?= __('Current Pot: %1', $block->getCurrentPot()) ?> </div>
<?php elseif ($block->isFinished()): ?>
    <div>

    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "[data-role=angel-countdown]": {
            "angelCountdown": {}
        }
    }
</script>