<?php
/** @var $block \Angel\Fifty\Block\Fifty\Sidebar */
/** @var  $getListFinishedFifty */
$getListFinishedFifty = $block->getFinishedFifty();
?>
<?php if($getListFinishedFifty->getSize()): ?>
    <div class="block block-layered-nav finished-Fifty">
        <div class="block-title">
            <strong><span><?= __('Finished 50/50 Raffle') ?></span></strong>
        </div>
        <ul class="fifty_list" style="list-style: none; padding-left: 3px;">
            <?php foreach ($getListFinishedFifty as $item): ?>
                <li>
                    <span><a href="<?= $block->getUrl('catalog/product/view', array('id'=> $item->getId())) ?>"><?= $item->getName() ?></a> </span>
                    <br/>
                    <span><?= $item->getWinningNumber() ?></span><br/>
                    <span><?= $block->formatPrice($item->getWinningPrize()) ?></span>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>