<?php
/**
 * Angel Fifty Raffles
 * Copyright (C) 2018 Mark Wolf
 *
 * This file included in Angel/Fifty is licensed under OSL 3.0
 *
 * http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * Please see LICENSE.txt for the full text of the OSL 3.0 license
 */

namespace Angel\Fifty\Block\Index;

use Angel\Fifty\Model\Product\Attribute\Source\FiftyStatus;

class Finished extends \Angel\Fifty\Block\Fifty
{
    protected function _getProductCollection()
    {
        $collection = parent::_getProductCollection();
        $collection->addAttributeToFilter('fifty_status', FiftyStatus::STATUS_FINISHED);
        return $collection; // TODO: Change the autogenerated stub
    }
}
